language: cpp
addons:
  apt:
    packages:
    - cmake
    - gcc-8
    - g++-8

before_script:
- sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 800 --slave /usr/bin/g++ g++ /usr/bin/g++-8
- sudo apt-get install libboost-test-dev -y
- echo "deb http://archive.ubuntu.com/ubuntu xenial main universe" | sudo tee -a /etc/apt/sources.list
- sudo apt-get update -qq
script:
- cmake .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  script:
          - curl -T ip_filter-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -uinlineboss:$BINTRAY_API_KEY "https://api.bintray.com/content/inline-boss/otus_ci-cd/ip_filter/$TRAVIS_BUILD_NUMBER/ip_filter-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"                                                                                       
