addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-8
      - g++-8
      - cmake

before_script:
- sudo apt-get install libboost-test-dev -y
- echo "deb http://archive.ubuntu.com/ubuntu xenial main universe" | sudo tee -a /etc/apt/sources.list
- sudo apt-get update -qq
- sudo apt-get install libgtest-dev
- sudo apt-get install cmake
- sudo apt-get update -qq
script:
# Link gcc-6 and g++-6 to their standard commands
- sudo ln -s /usr/bin/gcc-8 /usr/local/bin/gcc
- sudo ln -s /usr/bin/g++-8 /usr/local/bin/g++
# Export CC and CXX to tell cmake which compiler to use
- export CC=/usr/bin/gcc-8
- export CXX=/usr/bin/g++-8
# Check versions of gcc, g++ and cmake
- gcc -v && g++ -v && cmake --version
# Run your build commands next
- cd /usr/src/gtest
- sudo cmake CMakeLists.txt
- sudo make
- sudo cp *.a /usr/lib
- cd -
- cmake .
- make 
- cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  script:
          - curl -T ip_filter-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -uinlineboss:$BINTRAY_API_KEY "https://api.bintray.com/content/inline-boss/otus_ci-cd/ip_filter/$TRAVIS_BUILD_NUMBER/ip_filter-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"                                                                                       
